server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "frame-src *;";
    add_header X-Frame-Options "";

    location / {
        try_files $uri $uri/ /index.html;
    }
}
